### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by luan-phan-onpage** [humazed/google_map_location_picker#1]
I got this one in step of installing this package
```
`google_map_location_picker` does not specify a Swift version and none of the targets (`Runner`) integrating it have the
    `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that
    integrate this pod.
```

**Comment by humazed** [comment]
This problem happens with all Swift plugins.
flutter/flutter#25676

It seems to work with the following

Bridging Header must be created.
Open the project with XCode. Then choose File -> New -> File -> Swift File.
A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.). XCode will ask you if you wish to create Bridging Header, click yes.
Make sure you have use_frameworks! in the Runner block, in ios/Podfile。
Make sure you have SWIFT_VERSION 4.2 selected in you XCode -> Build Settings
Do flutter clean
Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update

from ko2ic/image_downloader/issues/9

if this doesn't solve your problem feel free to reopen it.
