### ISSUE TITLE
set value to initialCenter is not working

### ISSUE THREAD

**Issue by moriswala** [humazed/google_map_location_picker#24]
Hi,

Thank you for the wonderful library. 

I want to use this library in one of my flutter project. I am able to use a location picker(add location) but I want to use the same picker to allow user to change location. 
For that I tried to use it like below:

```
LatLng location = getLatLng(state.latLng);
result = await LocationPicker.pickLocation(
        context,
        Constants.GOOGLE_API_KEY,
        initialCenter: location,
);
```

but unfortunately its not pinned to specified location and always showing my current location.
How can I set the pinned location while initiating picker ?

**Comment by Dararii** [comment]
Same issue here

**Comment by moriswala** [comment]
Since no update on this I decided to continue developing using another plugin https://pub.dev/packages/place_picker

Hope it will help you.

**Comment by Dararii** [comment]
Thank you so much, I'll definitely try that plugin.

**Comment by humazed** [comment]
The `initialCenter` works as expected and as long as the current user location is known the map is animated to it.
I think adding a flag to configure this behavior is what you want. 

I will add `automaticallyAnimateToCurrentLocation`

**Comment by humazed** [comment]
Added `automaticallyAnimateToCurrentLocation` in `3.1.0` if this doesn't solve your problem feel free to reopen.

**Comment by kamal0808** [comment]
Hi @humazed , the new option `automaticallyAnimateToCurrentLocation` is able to animate to the current location, but it shows the animation moving from the initial position that is hardcoded `const LatLng(45.521563, -122.677433),`. This might confuse the user as to why his map initially shows a location in Poland, and then animates to his own location.
Can you please include a variable `initialCenter` so that the map can initially show the current user location?

**Comment by Anna225** [comment]
@humazed I have got the issue same to above.
I added initialCenter option but it doesn't work.
Could you help me?
![image](https://user-images.githubusercontent.com/49732009/96666431-c998fe80-135f-11eb-8408-f1522c3f11d2.png)
